### PR TITLE
Make it node compatible

### LINKED ISSUE #6: Not working in node
XMLHttpRequest and btoa are expected to be on globals and don't work.

### PR DESCRIPTION
**Pull request by otaviosoares**
fixes #6

### CODE REVIEW

File: lib/resources/Account.js [hunk 1]
```diff
@@ -1,151 +1,176 @@
...
+                callback = params;
+                params = {};
+            }
+            var options = {user: user, reason: reason, comment: comment};
+            _delete(Account.ACCOUNT_RESOURCE + '/' + id + '/emails/' + email.email, params, options, callback);
+        }
+
+    };
+
+    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined')
```
Comment (pierre) [inline lib/resources/Account.js]: Just for style, could you add the braces explicitly?

File: lib/resources/Payment.js [hunk 2]
```diff
@@ -1,7 +1,29 @@
...
+
+    var Payment = {
+        PAYMENT_RESOURCE: BASE_RESOURCE + '/payments',
+
+        getByAccountId: function(accountId, callback) {
+            _get(Account.ACCOUNT_RESOURCE + '/' + accountId + '/payments', {}, {}, callback);
+        }
+    };
+
+    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined')
```
Comment (pierre) [inline lib/resources/Payment.js]: Same remark regarding style.

File: lib/resources/Security.js [hunk 3]
```diff
@@ -1,20 +1,42 @@
...
+            if (typeof params === 'function') {
+                callback = params;
+                params = {};
+            }
+            _get(Security.SECURITY_RESOURCE + '/subject', params, {}, callback);
+        }
+
+    };
+
+    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined')
```
Comment (pierre) [inline lib/resources/Security.js]: Same remark regarding style.

File: lib/resources/Subscription.js [hunk 4]
```diff
@@ -1,118 +1,142 @@
...
-        params.tagList = tags.map(function (item) {
-            return item.tagDefinitionId;
-        }).join(',');
-        K._delete(K.Subscription.SUBSCRIPTION_RESOURCE + '/' + id + '/tags', params, options, callback);
-    }
 
-};
+    };
+
+    if (typeof module !== 'undefined' && typeof module.exports !== 'undefined')
```
Comment (pierre) [inline lib/resources/Subscription.js]: Same remark regarding style.

File: lib/resources/Account.js [hunk 5]
```diff
@@ -1,151 +1,176 @@
...
-
-    removeEmail: function (id, email, user, reason, comment, params, callback) {
-        if (typeof params === 'function') {
-            callback = params;
-            params = {};
-        }
-        var options = {user: user, reason: reason, comment: comment};
-        K._delete(K.Account.ACCOUNT_RESOURCE + '/' + id + '/emails/' + email.email, params, options, callback);
+(function(exports){
+    var BASE_RESOURCE = exports.BASE_RESOURCE;
```
Comment (pierre) [inline lib/resources/Account.js]: Question: would it be easier to read/maintain if these were in an `else` block?

```
if (typeof require !== 'undefined') {
   var _post = ...
} else {
   var _post = ...
}
```

That way, they are only declared once?
